### ISSUE TITLE
Please store access token in flows_cred.json

### ISSUE THREAD

**Issue by parasaurolophus** [fblackburn1/node-red-contrib-hubitat#20]
Please put sensitive configuration information in flows_cred.json so that it will not be exported directly with the rest of the flow information and encrypted by default.

**Comment by Botched1** [comment]
Agreed. That would be appropriate/better.

**Comment by fblackburn1** [comment]
Agreed. I'm glad you brought the topic
I've already look at it, but finally decided to stop working on it:
* no one request it
* no real advantage (I mean all information are only valid on local network)
* upgrade will break all configurations

Which information do you want in this credential type? Only token? Or you consider that IP is sensitive too? If so, then port and SSL/TLS would be too? What's about application ID?

**Comment by parasaurolophus** [comment]
Perhaps so. :-)

The only two I personally would consider essential are the access token and, for the reason you mention, the webhook. But for consistency and ease of implementation I would not object to the whole configuration being stored in flows_cred.json. I do not see that as burdensome since all of the values would have to be altered by anyone with whom I shared one of my flows, in any event.

Thanks

**Comment by fblackburn1** [comment]
I checked some popular nodes and read threads and my conclusion is that setting all other properties (except  token/appID and webhook path) as credentials would be a bad design because the import/export feature can be used in several ways:
* share flow between people
* backup flow
* share flow on the same infrastructure
For these reasons, adding IP/port/etc.. as credentials to only remove them from export would not be a good reason

I consider that token and application ID (which is like a username) being secret.
It would have the consequence do not have the possibility to see the token after first set (because password type is not accessible via the editor).

To keep consistency, if we consider token being secret, then the webhook path is also a secret, because it allows to inject any event without authentication. For this reason, I would replace the default webhook path with a generated uuid and transform this field to a credential too (but credentials of text type to continue to see it in the editor)

(It's mostly what you suggest, I only want to be more explicit if we need reference)

**Comment by fblackburn1** [comment]
After changing my mind a lot of time, I decided to not consider the Application ID as a username, but simply to consider its link with the token an implementation detail.

In addition, I also learned that it is possible to do basic auth with HE. So I no longer consider the webhookPath to be a secret, because the giving use case do not make sense anymore

So, I come back to your initial request with only the token being a credential :sweat_smile:
