### ISSUE TITLE
Entire global cache rebuilds any time a device or command node is opened in node-red

### ISSUE THREAD

**Issue by Botched1** [fblackburn1/node-red-contrib-hubitat#60]
Found what I consider a serious bug.

With Maker API debug logging turned on, I found that any time you double click on a command or device node in node-red, whether you change anything or not, the complete hubitat global cache gets rebuilt. It happens immediately after you double click on a command or device node.

This creates tremendous load on the hub as I've seen that when editing a few nodes, it may re-initialize the entire cache a dozen or more times...

EDIT: Maybe this is by deisgn, and it is just the /devices call that is generating all of the Maker API log entries?

![image](https://user-images.githubusercontent.com/19985320/92277711-2f691e00-eeb9-11ea-8b74-958202b61057.png)

**Comment by fblackburn1** [comment]
When you double click on command node, it will trigger two requests to HE
```
http://<HE_IP>/apps/api/<app_id>/devices?access_token=<token>
http://<HE_IP>/apps/api/<app_id>/devices/<device-id>/commands?access_token=<token>
```
When I tested manually (i.e. enter these url in the browser), I have the following result:
* first url
![Screenshot from 2020-09-05 14-37-38](https://user-images.githubusercontent.com/11160579/92311485-6a388800-ef85-11ea-8812-00d31a524e79.png)
* second url
![Screenshot from 2020-09-05 14-39-37](https://user-images.githubusercontent.com/11160579/92311529-c69ba780-ef85-11ea-8800-50ba0c542ae8.png)
But I only have 6 devices on my HE, so maybe with more device is more freaking. Can you test it manually?

Otherwise there is no reason that editing (without deploying) invalid/rebuild cache, in the NodeRED core code, these two concepts are quite distinct
